name: Python Code Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip3 install requests
          pip3 install boto3
          pip3 install flask
      - name: Python test
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_ACCESS_KEY_SECRET=${{ secrets.AWS_ACCESS_KEY_SECRET }}
          export AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
          export AWS_BUCKET_KEY=${{ secrets.AWS_BUCKET_KEY }}
          python uploadTest.py
